In [7]:
import numpy as np
m=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(m)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Numpy does withoout <b>actually moving any data in memory</b>. it simply changes the way it indexes the orginal matrix.
So its effecient

In [14]:
#traspose
m.T

array([[  1,   5,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4, 200,  12]])

In [15]:
#Note we need to be careful for sharing the same data.
#Here we notice that even m_t is also modified.
m_t=m.T
m_t[3][1] = 200
m_t
print(m)
print(m_t)

[[  1   2   3   4]
 [  5   6   7 200]
 [  9  10  11  12]]
[[  1   5   9]
 [  2   6  10]
 [  3   7  11]
 [  4 200  12]]


In [20]:
inputs =np.array([[-0.27,0.45,0.64,0.31]])

weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

print(inputs)
inputs.shape
print(weights)
weights.shape

[[-0.27  0.45  0.64  0.31]]
[[ 0.02   0.001 -0.03   0.036]
 [ 0.04  -0.003  0.025  0.009]
 [ 0.012 -0.045  0.28  -0.067]]


(3, 4)

In [21]:
np.matmul(inputs,weights)

ValueError: shapes (1,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [23]:
# This would work, if take the transpose
# which multiplication depends on the weight
np.matmul(inputs,weights.T)
np.matmul(weights,inputs.T)

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])